STATUS: present
NAMESPACE: default
SERVICE:
  NAME: keydb
  OPENSHIFT: false
  ENV:
    KEYDB_PASSWORD: "123456"
  IMAGE:
    NAME: dimaskiddo/alpine:keydb-6.2
  RESOURCES:
    LIMITS:
      CPU: 1
      MEMORY: 256Mi
  SELECTOR:
    NODE: ""
  STORAGE:
    CAPACITY: 1Gi
