{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: "ClusterIP"
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: tcp-27017
  selector: 
      app: {{ .Values.SERVICE.NAME }} 
  {{- end }}
{{- else }}
# Delete Service
{{- end }}
