{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE.NAME }}-env
  namespace: {{ .Values.NAMESPACE }}
type: Opaque
stringData:
  TZ: "Asia/Jakarta"
  KAFKA_CONF_ADVERTISED_LISTENERS: "PLAINTEXT://{{ .Values.SERVICE.NAME }}:9092"  
    {{- if .Values.SERVICE.ENV }}
      {{- range $key, $val := .Values.SERVICE.ENV }}
  {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- else }}
# Delete Secret
{{- end }}
