STATUS: present
NAMESPACE: default
SERVICE:
  NAME: service-name
  PORT: 9000
  STRATEGY: rolling
  USE_DATADOG: false
  IMAGE:
    NAME: my-image/service-name:latest
    SECRET: service-registry
  RESOURCES:
    REPLICAS: 1
    LIMITS:
      CPU: 100m
      MEMORY: 256Mi
  HPA:
    MIN_REPLICAS: 1
    MAX_REPLICAS: 3
    METRICS:
      AVG_CPU_PERCENTAGE_UTILIZATION: 90
      AVG_MEMORY_PERCENTAGE_UTILIZATION: 80
  SELECTOR:
    NODE: ""
  ALIASES:
    - IP: 127.0.0.1
      HOSTNAMES:
        - local.example.com
