STATUS: present
OPENSHIFT: false
NAMESPACE: default
SERVICE:
  NAME: rabbitmq
  ENV:
    RABBITMQ_CONF_default__user: user
    RABBITMQ_CONF_default__pass: 123456
  IMAGE:
    NAME: dimaskiddo/alpine:rabbitmq-3.7-management
  RESOURCES:
    LIMITS:
      CPU: 1
      MEMORY: 512Mi
  SELECTOR:
    NODE: ""
  STORAGE:
    CAPACITY: 5Gi
