{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
    {{- if .Values.OPENSHIFT }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
    {{- else }}
apiVersion: apps/v1
kind: Deployment
    {{- end }}
metadata:
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Values.SERVICE.NAME }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  strategy:
  {{- if eq .Values.SERVICE.STRATEGY "rolling" }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  {{- else }}
    type: Recreate
  {{- end }}
  {{- if .Values.SERVICE.RESOURCES }}
    {{- if .Values.SERVICE.RESOURCES.REPLICAS }}
  replicas: {{ .Values.SERVICE.RESOURCES.REPLICAS }}
    {{- else }}
  replicas: 0
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.SERVICE.NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.SERVICE.NAME }}
        date: "{{ now | unixEpoch }}"  
    spec:
      containers:
      - name: {{ .Values.SERVICE.NAME }}
        image: {{ .Values.SERVICE.IMAGE.NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.SERVICE.PORT }}
          protocol: TCP
        {{- if .Values.SERVICE.ENV }}
        envFrom:
        - secretRef:
            name: {{ .Values.SERVICE.NAME }}-env
        {{- end }}
        {{- if .Values.SERVICE.RESOURCES }}
        resources:
          requests:
          {{- if .Values.SERVICE.RESOURCES.REQUESTS }}
            {{- if .Values.SERVICE.RESOURCES.REQUESTS.CPU }}
            cpu: {{ .Values.SERVICE.RESOURCES.REQUESTS.CPU }}
            {{- end }}
            {{- if .Values.SERVICE.RESOURCES.REQUESTS.MEMORY }}
            memory: {{ .Values.SERVICE.RESOURCES.REQUESTS.MEMORY }}
            {{- end }}
          {{- else }}
            {{- if .Values.SERVICE.RESOURCES.LIMITS.CPU }}
            cpu: {{ .Values.SERVICE.RESOURCES.LIMITS.CPU }}
            {{- end }}
            {{- if .Values.SERVICE.RESOURCES.LIMITS.MEMORY }}
            memory: {{ .Values.SERVICE.RESOURCES.LIMITS.MEMORY }}
            {{- end }}
          {{- end }}
          {{- if .Values.SERVICE.RESOURCES.LIMITS }}
          limits:
            {{- if .Values.SERVICE.RESOURCES.LIMITS.CPU }}
            cpu: {{ .Values.SERVICE.RESOURCES.LIMITS.CPU }}
            {{- end }}
            {{- if .Values.SERVICE.RESOURCES.LIMITS.MEMORY }}
            memory: {{ .Values.SERVICE.RESOURCES.LIMITS.MEMORY }}
            {{- end }}
          {{- end }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.SERVICE.PORT }}
          timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: {{ .Values.SERVICE.PORT }}
          timeoutSeconds: 1        
      dnsPolicy: ClusterFirst
      {{- if .Values.SERVICE.IMAGE }}
        {{- if .Values.SERVICE.IMAGE.SECRET }}
      imagePullSecrets:
       - name: {{ .Values.SERVICE.IMAGE.SECRET }}
        {{- end }}
      {{- end }}
      {{- if .Values.SERVICE.SELECTOR }}
      nodeSelector:
        {{- if .Values.SERVICE.SELECTOR.NODE }}
        node-role.kubernetes.io/worker: "{{ .Values.SERVICE.SELECTOR.NODE }}"
        {{- end }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
  {{- end }}
{{- else }}
# Delete Deployment
{{- end }}
