{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.SERVICE.PORT }}
      targetPort: {{ .Values.SERVICE.PORT }}
      protocol: TCP
      name: tcp-{{ .Values.SERVICE.PORT }}
  selector: 
      app: {{ .Values.SERVICE.NAME }} 
  {{- end }}
{{- else }}
# Delete Service
{{- end }}
