{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: "ClusterIP"
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: tcp-9200
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: tcp-9300
  selector: 
      app: {{ .Values.SERVICE.NAME }} 
  {{- end }}
{{- else }}
# Delete Service
{{- end }}
