STATUS: present
NAMESPACE: default
SERVICE:
  NAME: kafka
  OPENSHIFT: false
  IMAGE:
    NAME: dimaskiddo/alpine:kafka-2.8
  RESOURCES:
    LIMITS:
      CPU: 1
      MEMORY: 512Mi
  SELECTOR:
    NODE: ""
  STORAGE:
    CAPACITY: 5Gi
