STATUS: present
NAMESPACE: default
SERVICE:
  NAME: redis
  OPENSHIFT: false
  ENV:
    REDIS_PASSWORD: "123456"
  IMAGE:
    NAME: dimaskiddo/alpine:redis-6.2
  RESOURCES:
    LIMITS:
      CPU: 1
      MEMORY: 256Mi
  SELECTOR:
    NODE: ""
  STORAGE:
    CAPACITY: 1Gi
